-- ============================================================
-- PRINTWAY PACKAGING ERP — Database Setup
-- Run this once inside your Supabase project's SQL Editor.
-- ============================================================

-- Clean reset (safe to re-run)
DROP TABLE IF EXISTS ledger_entries CASCADE;
DROP TABLE IF EXISTS clients CASCADE;

-- 1. CLIENT / PROFILE REGISTRY (suppliers for purchase, buyers for sales)
CREATE TABLE clients (
  client_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name     text NOT NULL,
  proprietor_name  text,
  mobile_number    text,
  location_address text,
  opening_balance  numeric(15, 2) DEFAULT 0.00,
  sector_type      text NOT NULL CHECK (sector_type IN ('purchase', 'sales')),
  created_at       timestamptz DEFAULT timezone('utc'::text, now())
);

-- 2. LEDGER TRANSACTION ROWS
CREATE TABLE ledger_entries (
  entry_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id    bigint REFERENCES clients(client_id) ON DELETE CASCADE NOT NULL,
  entry_date   date NOT NULL,
  challan_no   text,
  description  text NOT NULL,
  bank_cash    text,
  quantity     numeric(12, 2) DEFAULT 0.00,
  sales_price  numeric(12, 2) DEFAULT 0.00,
  total_price  numeric(15, 2) DEFAULT 0.00,
  paid_amount  numeric(15, 2) DEFAULT 0.00,
  created_at   timestamptz DEFAULT timezone('utc'::text, now())
);

-- ============================================================
-- SECURITY: Row Level Security STAYS ON.
-- Only signed-in staff (any authenticated Supabase Auth user)
-- can read or write. No public/anon access at all.
-- ============================================================
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "staff_read_clients" ON clients
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "staff_write_clients" ON clients
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "staff_update_clients" ON clients
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "staff_delete_clients" ON clients
  FOR DELETE TO authenticated USING (true);

CREATE POLICY "staff_read_ledger" ON ledger_entries
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "staff_write_ledger" ON ledger_entries
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "staff_update_ledger" ON ledger_entries
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "staff_delete_ledger" ON ledger_entries
  FOR DELETE TO authenticated USING (true);

-- No GRANT statements to `anon` — anonymous/public users get nothing.
-- Only `authenticated` (i.e. logged-in) users can touch these tables.

-- ============================================================
-- NEXT STEP: create staff accounts
-- Go to Authentication → Users → "Add user" in the Supabase
-- dashboard and create one login per staff member (email + password).
-- They will use these credentials to log into the ERP app.
-- ============================================================
